preset: recommended
risky: true
enabled:
  - align_double_arrow_minimal
  # - align_equals_minimal
  # - date_time_immutable
  - ereg_to_preg
  - function_to_constant
  # - mb_str_functions
  - modernize_types_casting
  # - native_function_invocation
  - no_blank_lines_after_return
  - no_homoglyph_names
  - no_php4_constructor
  - no_useless_else
  - phpdoc_add_missing_param_annotation
disabled:
  - align_double_arrow
  - blank_line_before_return
  # - hash_to_slash_comment
  - phpdoc_summary
  - phpdoc_var_without_name
  # - unalign_equals
finder:
  exclude:
    - node_modules
    - storage
    - vendor
  name: "*.php"
  not-name: "*.blade.php"
