#
# Initial minimal data required. You probably don't
# want to modify or erase any of this here
#

airports:
  - id: KAUS
    iata: AUS
    icao: KAUS
    name: Austin-Bergstrom
    location: Austin, Texas, USA
    country: United States
    timezone: America/Chicago
    lat: 30.1945278
    lon: -97.6698889
    hub: 1
