name: docker-push

on:
  pull_request:
    types: closed
    branches:
      - 'master'
      - 'dev'
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - '!.github/**'
  workflow_dispatch:

jobs:
  build-variables:
    runs-on: ubuntu-latest
    outputs:
      githubsha: ${{ steps.extract-sha.outputs.shortsha }}
      gitbranch: ${{ steps.gitbranch.outputs.gitbranch }}
    strategy:
      fail-fast: true
    steps:
      - name: Extract SHA and store in output var
        run: echo "##[set-output name=shortsha;]$(echo ${GITHUB_SHA} | cut -c1-7)"
        id: extract-sha

      - name: Extract Git branch name and store in output var
        run: echo "##[set-output name=gitbranch;]$(echo ${GITHUB_REF##*/})"
        id: gitbranch

  docker:
    needs: [build-variables]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/phpvms:${{ needs.build-variables.outputs.gitbranch }},${{ secrets.DOCKERHUB_USERNAME }}/phpvms:${{ needs.build-variables.outputs.gitbranch }}-${{ needs.build-variables.outputs.githubsha }}
