name: 'Run Tests'
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }}
    env:
      extensions: intl, pcov, mbstring
      key: cache-v1 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup cache environment
      id: cache-env
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }}
        key: ${{ env.key }}
    - name: Cache extensions
      uses: actions/cache@v1
      with:
        path: ${{ steps.cache-env.outputs.dir }}
        key: ${{ steps.cache-env.outputs.key }}
        restore-keys: ${{ steps.cache-env.outputs.key }}
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ${{ env.extensions }}
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug
        tools: php-cs-fixer, phpunit
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop 
    - uses: getong/mariadb-action@v1.1
      with:
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql database: 'phpvms'
        mysql root password: ''
        mysql user: ''
        mysql password: ''
    - name: Configure Environment
      run: |
        php --version
        mysql --version
        # add npm packages
        sudo npm i tar-to-zip -g
        # Downgrade composer version to 1.x
        composer self-update --1
        composer install --dev --no-interaction --verbose
        cp .travis/env.travis.php env.php
        cp .travis/phpunit.travis.xml phpunit.xml
        php artisan database:create --reset
        php artisan migrate:refresh --seed
    - name: Run Tests
      run: |
        vendor/bin/php-cs-fixer fix --config=.php_cs -v --dry-run --diff --using-cache=no
        vendor/bin/phpunit --debug --verbose
  artifacts:
    needs: build
    runs-on: 'ubuntu-18.04'
    #if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
    steps:
      - name: 'Cleanup'
        run: ./.github/scripts/cleanup.sh
      - name: 'Build Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            **
